hf_trainer:
  evaluation_strategy: epoch
  save_strategy: epoch
  learning_rate: 1e-3
  per_device_train_batch_size: 16
  per_device_eval_batch_size: 16
  num_train_epochs: 15
  weight_decay: 0.01
  load_best_model_at_end: True

train_classifier_layer_only: False
limit_train_dataset: 1.0
limit_test_dataset: 1.0