hf_trainer:
  evaluation_strategy: epoch
  save_strategy: epoch
  learning_rate: 2e-5
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 32
  num_train_epochs: 10
  weight_decay: 0.01
  load_best_model_at_end: True

train_classifier_layer_only: False
limit_train_dataset: 1
limit_test_dataset: 1