hf_trainer:
  evaluation_strategy: epoch
  save_strategy: epoch
  learning_rate: 3e-4
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  num_train_epochs: 5
  weight_decay: 0.01
  load_best_model_at_end: True

train_classifier_layer_only: True