hf_trainer:
  evaluation_strategy: steps
  eval_steps: 32
  save_steps: 640
  save_strategy: steps
  learning_rate: 1e-3
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  num_train_epochs: 1
  weight_decay: 0.01
  load_best_model_at_end: True

train_classifier_layer_only: True
limit_train_dataset: 0.1
limit_test_dataset: 0.1